[package]
name = "rust-lisp"
version = "0.1.0"
authors = ["brundolf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-lisp"
path = "main.rs"
